name: hebrew-greek-tts
type: docker-compose
description: "Hebrew & Greek TTS API optimized for production"

services:
  - name: hebrew-greek-tts
    image: hebrew-greek-tts:latest
    port: 8000
    healthcheck: "/health"
    
environments:
  production:
    variables:
      LOG_LEVEL: "info"
      PORT: "8000"
      WORKERS: "1"
    domains:
      - "your-domain.com"  # Substitua pelo seu domínio
    
resources:
  memory: "2GB"
  cpu: "1"
  
volumes:
  - "/opt/hebrew-greek-tts/cache:/home/app/.cache"
  - "/opt/hebrew-greek-tts/logs:/home/app/logs"